CONFIG_SHELL=y
CONFIG_BOOT_BANNER=y
CONFIG_SENSOR=y
CONFIG_SENSOR_SHELL=y
CONFIG_SENSOR_SHELL_STREAM=y
CONFIG_SENSOR_INFO=y
CONFIG_SEN6X_SHELL=y
CONFIG_NET_BUF=y

CONFIG_LOG=y
CONFIG_RTIO_CONSUME_SEM=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8096
CONFIG_MAIN_STACK_SIZE=8096
CONFIG_ASSERT=y
# CONFIG_I2C_LOG_LEVEL_DBG=y
# CONFIG_NRFX_TWI_LOG=y
# CONFIG_LOG_BACKEND_UART=y
# CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_SHELL_STACK_SIZE=8096
CONFIG_LOG_BUFFER_SIZE=8096
CONFIG_SENSOR_SHELL_THREAD_STACK_SIZE=8096

CONFIG_NRFX_PRS_BOX_0=y
CONFIG_NRFX_PRS_BOX_1=y
CONFIG_NRFX_PRS_BOX_2=y
CONFIG_NRFX_PRS_BOX_3=y
CONFIG_NRFX_PRS_BOX_4=y

CONFIG_REBOOT=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_SHELL=y

